// @trace spec:user-runtime-lifecycle, spec:linux-native-portable-executable, spec:init-command
use std::fs;
use std::io::Write;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Eq, PartialEq)]
struct Asset {
    source: PathBuf,
    dest: String,
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crate lives under repo_root/crates/tillandsias-headless");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let generated = out_dir.join("runtime_assets_generated.rs");

    let mut assets = Vec::new();
    collect_assets(
        &repo_root.join("images"),
        &repo_root.join("images"),
        repo_root,
        "",
        &mut assets,
    );
    collect_assets(
        &repo_root.join("observatorium"),
        &repo_root.join("observatorium"),
        repo_root,
        "",
        &mut assets,
    );
    collect_assets(
        &repo_root.join("skills"),
        &repo_root.join("skills"),
        repo_root,
        "images/default/skills",
        &mut assets,
    );
    collect_assets(
        &repo_root.join("skills"),
        &repo_root.join("skills"),
        repo_root,
        "images/nanoclawv2/skills",
        &mut assets,
    );

    for rel in ["scripts/manage-cache.sh", "scripts/run-observatorium.sh"] {
        let path = repo_root.join(rel);
        if path.is_file() {
            assets.push(Asset {
                source: path.clone(),
                dest: rel.to_string(),
            });
        } else {
            panic!("required runtime asset missing: {}", path.display());
        }
    }

    assets.sort_by(|a, b| a.dest.cmp(&b.dest));

    for asset in &assets {
        println!("cargo:rerun-if-changed={}", asset.source.display());
    }
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("images").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("observatorium").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("skills").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("scripts/manage-cache.sh").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("scripts/run-observatorium.sh").display()
    );

    let required = [
        "images/default/Containerfile.base",
        "images/default/Containerfile",
        "images/proxy/Containerfile",
        "images/proxy/allowlist.txt",
        "images/git/Containerfile",
        "images/inference/Containerfile",
        "images/router/Containerfile",
        "images/router/base.Caddyfile",
        "images/router/tillandsias-router-sidecar",
        "images/chromium/Containerfile.core",
        "images/chromium/Containerfile.framework",
        "images/web/Containerfile",
        "observatorium/index.html",
        "scripts/manage-cache.sh",
        "scripts/run-observatorium.sh",
        "skills/advance-work-from-plan/SKILL.md",
    ];
    for rel in required {
        if !repo_root.join(rel).is_file() {
            panic!(
                "required runtime asset missing: {}",
                repo_root.join(rel).display()
            );
        }
    }

    let mut file = fs::File::create(&generated).unwrap();
    writeln!(file, "// Auto-generated by build.rs; do not edit.").unwrap();
    writeln!(file).unwrap();
    writeln!(
        file,
        "pub const EMBEDDED_RUNTIME_ASSETS: &[EmbeddedRuntimeAsset] = &["
    )
    .unwrap();

    for asset in assets {
        let abs = asset.source.to_string_lossy();
        let executable = is_executable(&asset.source);
        writeln!(
            file,
            "    EmbeddedRuntimeAsset {{ path: {:?}, bytes: include_bytes!({:?}), executable: {} }},",
            asset.dest, abs, executable
        )
        .unwrap();
    }

    writeln!(file, "];").unwrap();
}

fn collect_assets(
    dir: &Path,
    collection_root: &Path,
    repo_root: &Path,
    dest_prefix: &str,
    out: &mut Vec<Asset>,
) {
    if !dir.is_dir() {
        panic!(
            "required runtime asset directory missing: {}",
            dir.display()
        );
    }

    let mut entries = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        .map(|entry| entry.unwrap().path())
        .collect::<Vec<_>>();
    entries.sort();

    for path in entries {
        let meta = fs::symlink_metadata(&path)
            .unwrap_or_else(|e| panic!("metadata {}: {e}", path.display()));
        if meta.file_type().is_symlink() {
            panic!(
                "runtime assets must not contain symlinks: {}",
                path.display()
            );
        }

        let rel_repo = path
            .strip_prefix(repo_root)
            .expect("asset under repo root")
            .to_string_lossy()
            .replace('\\', "/");

        // Skip images/default/skills if we are collecting the images/ directory recursively.
        if dest_prefix.is_empty() && rel_repo.starts_with("images/default/skills") {
            continue;
        }

        if meta.is_dir() {
            collect_assets(&path, collection_root, repo_root, dest_prefix, out);
        } else if meta.is_file() {
            let dest = if !dest_prefix.is_empty() {
                let sub_rel = path
                    .strip_prefix(collection_root)
                    .expect("sub-asset under collection root")
                    .to_string_lossy()
                    .replace('\\', "/");
                format!("{dest_prefix}/{sub_rel}")
            } else {
                rel_repo.clone()
            };

            out.push(Asset { source: path, dest });
        }
    }
}

fn is_executable(path: &Path) -> bool {
    #[cfg(unix)]
    {
        fs::metadata(path)
            .map(|m| m.permissions().mode() & 0o111 != 0)
            .unwrap_or(false)
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        false
    }
}
