// @trace spec:user-runtime-lifecycle, spec:linux-native-portable-executable, spec:init-command
use std::fs;
use std::io::Write;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crate lives under repo_root/crates/tillandsias-headless");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let generated = out_dir.join("runtime_assets_generated.rs");

    let mut assets = Vec::new();
    collect_files(&repo_root.join("images"), &mut assets);
    collect_files(&repo_root.join("observatorium"), &mut assets);
    for rel in ["scripts/manage-cache.sh", "scripts/run-observatorium.sh"] {
        let path = repo_root.join(rel);
        if path.is_file() {
            assets.push(path);
        } else {
            panic!("required runtime asset missing: {}", path.display());
        }
    }

    assets.sort();

    for path in &assets {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("images").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("observatorium").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("scripts/manage-cache.sh").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("scripts/run-observatorium.sh").display()
    );

    let required = [
        "images/default/Containerfile.base",
        "images/default/Containerfile",
        "images/proxy/Containerfile",
        "images/proxy/allowlist.txt",
        "images/git/Containerfile",
        "images/inference/Containerfile",
        "images/router/Containerfile",
        "images/router/base.Caddyfile",
        "images/router/tillandsias-router-sidecar",
        "images/chromium/Containerfile.core",
        "images/chromium/Containerfile.framework",
        "images/web/Containerfile",
        "observatorium/index.html",
        "scripts/manage-cache.sh",
        "scripts/run-observatorium.sh",
    ];
    for rel in required {
        if !repo_root.join(rel).is_file() {
            panic!(
                "required runtime asset missing: {}",
                repo_root.join(rel).display()
            );
        }
    }

    let mut file = fs::File::create(&generated).unwrap();
    writeln!(file, "// Auto-generated by build.rs; do not edit.").unwrap();
    writeln!(file).unwrap();
    writeln!(
        file,
        "pub const EMBEDDED_RUNTIME_ASSETS: &[EmbeddedRuntimeAsset] = &["
    )
    .unwrap();

    for path in assets {
        let rel = path
            .strip_prefix(repo_root)
            .expect("asset under repo root")
            .to_string_lossy()
            .replace('\\', "/");
        let abs = path.to_string_lossy();
        let executable = is_executable(&path);
        writeln!(
            file,
            "    EmbeddedRuntimeAsset {{ path: {:?}, bytes: include_bytes!({:?}), executable: {} }},",
            rel, abs, executable
        )
        .unwrap();
    }

    writeln!(file, "];").unwrap();
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    if !dir.is_dir() {
        panic!(
            "required runtime asset directory missing: {}",
            dir.display()
        );
    }

    let mut entries = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        .map(|entry| entry.unwrap().path())
        .collect::<Vec<_>>();
    entries.sort();

    for path in entries {
        let meta = fs::symlink_metadata(&path)
            .unwrap_or_else(|e| panic!("metadata {}: {e}", path.display()));
        if meta.file_type().is_symlink() {
            panic!(
                "runtime assets must not contain symlinks: {}",
                path.display()
            );
        }
        if meta.is_dir() {
            collect_files(&path, out);
        } else if meta.is_file() {
            out.push(path);
        }
    }
}

fn is_executable(path: &Path) -> bool {
    #[cfg(unix)]
    {
        fs::metadata(path)
            .map(|m| m.permissions().mode() & 0o111 != 0)
            .unwrap_or(false)
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        false
    }
}
