#!/usr/bin/env bash
# =============================================================================
# Tillandsias — macOS tray build script
#
# Builds tillandsias-macos-tray for Apple Silicon, assembles the .app bundle
# with Info.plist substitution + ad-hoc codesign + virtualization entitlement,
# tars it into dist/, writes SHA256SUMS, and prints a one-line summary.
#
# Outputs:
#   dist/Tillandsias.app                                            (signed bundle)
#   dist/tillandsias-tray-<version>-macos-arm64.tar.gz              (release artifact)
#   dist/SHA256SUMS                                                 (line per artifact)
#
# Usage:
#   scripts/build-macos-tray.sh
#
# Prereqs: macOS (Apple Silicon), Rust toolchain with aarch64-apple-darwin
# target (= host triple on Apple Silicon), zig, cargo-zigbuild, codesign, tar,
# shasum.
#
# @trace spec:macos-tray-build-and-release, spec:macos-native-tray
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"
if command -v brew >/dev/null 2>&1 && brew --prefix rustup >/dev/null 2>&1; then
    PATH="$(brew --prefix rustup)/bin:$PATH"
fi
PATH="$HOME/.cargo/bin:$PATH"

say() { printf '  %s\n' "$*"; }
die() { printf '  ERROR: %s\n' "$*" >&2; exit 1; }

# ── 1. Host arch gate ────────────────────────────────────────────────────
[[ "$(uname -s)" == "Darwin" ]] || die "build-macos-tray.sh must run on macOS (uname -s is $(uname -s))"
[[ "$(uname -m)" == "arm64"  ]] || die "build host must be Apple Silicon (uname -m must be arm64; got $(uname -m))"

# ── 2. Toolchain check ───────────────────────────────────────────────────
command -v cargo    >/dev/null || die "cargo not in PATH (install Rust: https://rustup.rs)"
command -v codesign >/dev/null || die "codesign not in PATH (install Xcode Command Line Tools)"
command -v shasum   >/dev/null || die "shasum not in PATH"
command -v zig      >/dev/null || die "zig not in PATH (install via brew install zig)"
command -v cargo-zigbuild >/dev/null || die "cargo-zigbuild not in PATH (install via cargo install cargo-zigbuild)"

# Apple Silicon is the host triple, so 'cargo build --release' is enough; an
# explicit --target aarch64-apple-darwin produces the same binary but adds
# a different output path. We use --release without --target.

# ── 3. Resolve version ──────────────────────────────────────────────────
[[ -f VERSION ]] || die "VERSION file not found at $ROOT/VERSION"
VERSION="$(cat VERSION | tr -d '[:space:]')"
VERSION_SHORT="$(echo "$VERSION" | cut -d. -f1-2)"
MIN_MACOS="14.0"
say "version: $VERSION  short: $VERSION_SHORT  min_macos: $MIN_MACOS"

# ── 3b. Stage the router sidecar ────────────────────────────────────────
# MUST run before the first cargo invocation. tillandsias-headless/build.rs
# lists images/router/tillandsias-router-sidecar in its `required` runtime
# assets (build.rs:93) and panics at build.rs:104 when it is absent.
#
# Order 710-w9kc un-committed that binary and made it a build artifact, adding
# the staging call to build.sh (_stage_router_sidecar_if_compiling) and to
# scripts/build-image.sh:174 — but not here, and this script is the macOS
# product build. Nothing caught it because the removal only deletes the file
# from git: every host that had already built kept its copy on disk, so the
# break is invisible locally and certain on a fresh clone.
#
# Reproduced on this host 2026-08-13 by moving the artifact aside:
#   thread 'main' panicked at crates/tillandsias-headless/build.rs:104:13:
#   required runtime asset missing: .../images/router/tillandsias-router-sidecar
# — an error naming a runtime asset, for what is really a missing build step.
#
# Cheap to call unconditionally: build-sidecar.sh exits early when the staged
# binary is newer than the sidecar crates, Cargo.lock and VERSION.
say "staging router sidecar (build artifact — not committed) …"
bash "$ROOT/scripts/build-sidecar.sh" >&2

# ── 4. Build ────────────────────────────────────────────────────────────
say "cargo build --release -p tillandsias-macos-tray …"
cargo build --release -p tillandsias-macos-tray >&2

BIN_PATH="$ROOT/target/release/tillandsias-tray"
[[ -x "$BIN_PATH" ]] || die "expected binary at $BIN_PATH after release build"

# ── 5. Assemble .app bundle ─────────────────────────────────────────────
DIST="$ROOT/dist"
APP="$DIST/Tillandsias.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BIN_PATH" "$APP/Contents/MacOS/tillandsias-tray"

# Substitute Info.plist template.
TEMPLATE="$ROOT/crates/tillandsias-macos-tray/assets/Info.plist.template"
[[ -f "$TEMPLATE" ]] || die "Info.plist.template missing at $TEMPLATE"
sed \
    -e "s/@VERSION@/${VERSION}/g" \
    -e "s/@VERSION_SHORT@/${VERSION_SHORT}/g" \
    -e "s/@MIN_MACOS@/${MIN_MACOS}/g" \
    "$TEMPLATE" > "$APP/Contents/Info.plist"

# Icons: Use the PNGs generated by generate-icons.py.
ICON_ICNS_SRC="$ROOT/crates/tillandsias-macos-tray/assets/icon.icns"
TRAY_ICON_SRC="$ROOT/crates/tillandsias-macos-tray/assets/tray-icon.png"

if [[ -f "$ICON_ICNS_SRC" ]]; then
    cp "$ICON_ICNS_SRC" "$APP/Contents/Resources/icon.icns"
fi

if [[ -f "$TRAY_ICON_SRC" ]]; then
    cp "$TRAY_ICON_SRC" "$APP/Contents/Resources/tray-icon.png"
fi

# Guest binaries: bundle the matching Linux headless build for both supported
# guest architectures so the tray can stage the exact same revision into the
# shared host tree before VM boot.
GUEST_DIR="$APP/Contents/Resources/guest"
mkdir -p "$GUEST_DIR"

build_guest_binary() {
    local target="$1"
    local asset_name="$2"
    local bin_path="$ROOT/target/${target}/release/tillandsias"
    say "cargo zigbuild --release -p tillandsias-headless --features listen-vsock --target ${target} …"
    cargo zigbuild --release -p tillandsias-headless --features listen-vsock --target "$target" --bin tillandsias >&2
    [[ -x "$bin_path" ]] || die "expected guest binary at $bin_path after zigbuild"
    cp "$bin_path" "$GUEST_DIR/$asset_name"
    chmod 0755 "$GUEST_DIR/$asset_name"
    # Mirror into the canonical target-guest/ staging so the
    # litmus:guest-binary-embed-integrity contract (scripts/
    # build-guest-binaries.sh --verify) holds on macOS-built checkouts too
    # — this script bypasses build-guest-binaries.sh, and an empty
    # target-guest/ failed that litmus on every macOS host sweep.
    install -m 0755 "$bin_path" "$ROOT/target-guest/$asset_name"
}
mkdir -p "$ROOT/target-guest"

build_guest_binary "aarch64-unknown-linux-musl" "tillandsias-headless-aarch64-unknown-linux-musl"
build_guest_binary "x86_64-unknown-linux-musl" "tillandsias-headless-x86_64-unknown-linux-musl"

# ── 6. Ad-hoc codesign with entitlements ────────────────────────────────
ENTITLEMENTS="$ROOT/crates/tillandsias-macos-tray/assets/Tillandsias.entitlements"
[[ -f "$ENTITLEMENTS" ]] || die "Tillandsias.entitlements missing at $ENTITLEMENTS"
# SIGNING IDENTITY. Ad-hoc by default — that is what a machine without a
# Developer ID can do, and it is enough: com.apple.security.virtualization is
# NOT a restricted entitlement, so an ad-hoc signature runs VZ fine (vfkit,
# lima and Code-Hex/vz all ship this way). What ad-hoc CANNOT do is satisfy
# Gatekeeper on a quarantined download, which is why install-macos.sh clears
# the attribute instead of arguing with it.
#
# Set TILLANDSIAS_MACOS_SIGN_IDENTITY to a "Developer ID Application: NAME
# (TEAMID)" string once enrollment completes and this becomes a real signature.
# UNSET, EVERY BYTE OF THE OLD BEHAVIOUR IS PRESERVED — the release path must
# not change shape on the day a credential appears in someone's keychain.
SIGN_IDENTITY="${TILLANDSIAS_MACOS_SIGN_IDENTITY:--}"

# get-task-allow lets a debugger attach; it is dev-only and NOTARIZATION
# REJECTS ANY BUILD CARRYING IT. Rather than keep two entitlement files that
# can drift, derive the release one by deleting that single key.
SIGN_ENTITLEMENTS="$ENTITLEMENTS"
if [[ "$SIGN_IDENTITY" != "-" ]]; then
    SIGN_ENTITLEMENTS="$(mktemp -t tillandsias-entitlements).plist"
    cp "$ENTITLEMENTS" "$SIGN_ENTITLEMENTS"
    /usr/libexec/PlistBuddy -c "Delete :com.apple.security.get-task-allow" \
        "$SIGN_ENTITLEMENTS" 2>/dev/null || true
    say "codesign (Developer ID: $SIGN_IDENTITY), get-task-allow stripped"
else
    say "codesign (ad-hoc) with $ENTITLEMENTS"
fi

# --timestamp is required for notarization and harmless ad-hoc, EXCEPT that an
# ad-hoc signature cannot carry one — so it is only added for a real identity.
if [[ "$SIGN_IDENTITY" != "-" ]]; then
    codesign --force --sign "$SIGN_IDENTITY" \
        --entitlements "$SIGN_ENTITLEMENTS" \
        --options runtime \
        --timestamp \
        "$APP" >&2
else
    codesign --force --sign - \
        --entitlements "$SIGN_ENTITLEMENTS" \
        --options runtime \
        "$APP" >&2
fi

# Verify
say "verify signature"
codesign --verify --deep --strict --verbose=2 "$APP" >&2

# Check entitlement present
ENTITLE_DUMP="$(codesign -d --entitlements - "$APP" 2>&1 || true)"
echo "$ENTITLE_DUMP" | grep -q 'com.apple.security.virtualization' \
    || die "com.apple.security.virtualization entitlement NOT present after sign"

# ── 6b. Notarize + staple (only with a real identity AND notary creds) ──
#
# Deliberately gated on BOTH: a Developer ID signature is necessary but not
# sufficient — Gatekeeper wants a notarization ticket too, and a stapled ticket
# is what makes the app open with no network. Absent either, this block is a
# no-op and the build is exactly what it was before.
#
# The ticket is stapled to the .app BEFORE the tarball is made: `stapler`
# cannot staple an archive, so stapling after packaging would silently produce
# an un-stapled release that works only while Apple's notary service is
# reachable — the kind of green that fails in someone else's airport lounge.
if [[ "$SIGN_IDENTITY" != "-" && -n "${TILLANDSIAS_NOTARY_KEY:-}" \
      && -n "${TILLANDSIAS_NOTARY_KEY_ID:-}" && -n "${TILLANDSIAS_NOTARY_ISSUER:-}" ]]; then
    command -v xcrun >/dev/null || die "xcrun not in PATH (needed to notarize)"
    NOTARY_ZIP="$DIST/Tillandsias-notarize.zip"
    say "notarize: submitting (this waits for Apple's verdict)"
    ditto -c -k --keepParent "$APP" "$NOTARY_ZIP"
    if ! xcrun notarytool submit "$NOTARY_ZIP" \
            --key "$TILLANDSIAS_NOTARY_KEY" \
            --key-id "$TILLANDSIAS_NOTARY_KEY_ID" \
            --issuer "$TILLANDSIAS_NOTARY_ISSUER" \
            --wait >&2; then
        rm -f "$NOTARY_ZIP"
        die "notarization FAILED — run: xcrun notarytool log <submission-id> --key ... for the reason"
    fi
    rm -f "$NOTARY_ZIP"
    say "notarize: stapling the ticket to the bundle"
    xcrun stapler staple "$APP" >&2 || die "stapler staple failed"
    # Prove it: this is the only check that distinguishes a notarized build
    # from a signed-but-unnotarized one, and it is the whole point of the step.
    spctl -a -vvv -t exec "$APP" >&2 || die "spctl assessment rejected the stapled app"
    say "notarize: accepted and stapled"
elif [[ "$SIGN_IDENTITY" != "-" ]]; then
    say "notarize: SKIPPED (identity set, but TILLANDSIAS_NOTARY_KEY/_KEY_ID/_ISSUER not all set)"
    say "          the app is Developer-ID signed but NOT notarized — Gatekeeper will still block a quarantined copy"
fi

# ── 7. Tarball + SHA256 ─────────────────────────────────────────────────
TAR_NAME="tillandsias-tray-${VERSION}-macos-arm64.tar.gz"
TAR_PATH="$DIST/$TAR_NAME"
( cd "$DIST" && tar -czf "$TAR_NAME" Tillandsias.app )

SHA="$(shasum -a 256 "$TAR_PATH" | awk '{print $1}')"
echo "${SHA}  ${TAR_NAME}" > "$DIST/SHA256SUMS"

# ── 8. Summary ──────────────────────────────────────────────────────────
SIZE_BYTES="$(stat -f%z "$TAR_PATH")"
SIZE_MB="$(echo "scale=2; $SIZE_BYTES / 1048576" | bc)"
say "built ${TAR_NAME} (${SIZE_MB} MiB, sha256 ${SHA})"
say "bundle: $APP"
say "tarball: $TAR_PATH"
