#!/usr/bin/env bash
# @trace spec:cheatsheet-tooling, spec:cheatsheets-license-tiered
#
# check-cheatsheet-frontmatter.sh — every authored cheatsheet must carry YAML
# frontmatter (order 782-avtk).
#
# WHY. methodology/cheatsheets.yaml -> cheatsheet_binding requires frontmatter
# "so the validator can classify tier, authority, status, provenance, and
# lifecycle metadata without relying on ad hoc filename heuristics" — but
# nothing enforced it, and cheatsheets/TEMPLATE.md (the file authors copy)
# taught a PROSE provenance section and no frontmatter at all. Following the
# template produced a sheet the canon rejects. One such sheet was already in
# the tree: runtime/forge-loss-on-shutdown-window.md carried HTML-comment
# provenance, so its tier, sources and last_verified were invisible to every
# frontmatter-parsing gate.
#
# This matters because the experts treat cheatsheets as ground truth
# (methodology.yaml -> cheatsheets_are_ground_truth_and_enforced_by_local_experts).
# A sheet no gate can classify is an uncitable claim wearing the same clothes
# as a verified one — worse than a missing sheet, because it looks covered.
#
# SCOPE: the AUTHORED tree only (cheatsheets/). The derived copy
# images/default/cheatsheets/ inherits frontmatter by construction and is
# guarded for equality by scripts/stage-image-cheatsheets.sh instead — see
# methodology/cheatsheets.yaml -> storage_and_authority.
#
# EXEMPT: INDEX.md (generated by regenerate-cheatsheet-index.sh; it is a
# directory listing, not a cheatsheet). TEMPLATE.md is NOT exempt — the whole
# point is that the template must produce what the canon requires.
#
# Output grammar (exactly one line):
#   ^(ok:cheatsheet-frontmatter:[0-9]+ checked|violation:missing-frontmatter:[0-9]+)$
#
# Usage:
#   scripts/check-cheatsheet-frontmatter.sh            # check the repo
#   scripts/check-cheatsheet-frontmatter.sh --selftest # fixtures, git-free
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# A file HAS frontmatter iff its very first line is exactly `---`. That is the
# YAML-document opener every parser in this repo keys on; a `---` further down
# is a horizontal rule, not frontmatter, so the check is deliberately strict
# about position rather than merely grepping for the token.
_has_frontmatter() {
    [[ "$(head -1 "$1")" == "---" ]]
}

_scan() {
    local dir="$1" checked=0 missing=0
    local -a offenders=()
    while IFS= read -r f; do
        case "$(basename "$f")" in
            INDEX.md) continue ;;
        esac
        checked=$((checked + 1))
        if ! _has_frontmatter "$f"; then
            missing=$((missing + 1))
            offenders+=("${f#"$dir"/}")
        fi
    done < <(find "$dir" -type f -name '*.md' | sort)

    if [[ "$missing" -gt 0 ]]; then
        printf 'violation:missing-frontmatter:%s\n' "$missing"
        printf '  %s\n' "${offenders[@]}" >&2
        printf 'Fix: copy the frontmatter block from cheatsheets/TEMPLATE.md and fill it in.\n' >&2
        return 1
    fi
    printf 'ok:cheatsheet-frontmatter:%s checked\n' "$checked"
    return 0
}

if [[ "${1:-}" == "--selftest" ]]; then
    # NEGATIVE CONTROL: the check must distinguish "frontmatter absent" from
    # "file merely contains a --- somewhere". Without this a horizontal rule
    # would satisfy the gate and the whole check would be decorative.
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT
    mkdir -p "$tmp/good" "$tmp/bad" "$tmp/hr"

    printf -- '---\ntags: [x]\n---\n# Title\n' > "$tmp/good/sheet.md"
    printf '# Title\n\n<!-- provenance: prose only -->\n' > "$tmp/bad/sheet.md"
    printf '# Title\n\nsome text\n\n---\n\nmore text\n' > "$tmp/hr/sheet.md"
    # INDEX.md is exempt even without frontmatter.
    printf '# Index\n' > "$tmp/good/INDEX.md"

    fail=0
    _scan "$tmp/good" >/dev/null 2>&1 || { echo "SELFTEST-FAIL: valid frontmatter rejected"; fail=1; }
    _scan "$tmp/bad" >/dev/null 2>&1 && { echo "SELFTEST-FAIL: missing frontmatter accepted"; fail=1; }
    _scan "$tmp/hr" >/dev/null 2>&1 && { echo "SELFTEST-FAIL: a horizontal rule was accepted as frontmatter"; fail=1; }

    if [[ "$fail" -ne 0 ]]; then
        echo "selftest:cheatsheet-frontmatter:FAIL"
        exit 1
    fi
    echo "selftest:cheatsheet-frontmatter:3 cases PASS"
    exit 0
fi

_scan "$ROOT/cheatsheets"
