#!/usr/bin/env bash
# @trace spec:project-bootstrap-readme
#
# check-skill-canonicalization.sh — every skill has exactly ONE source of truth.
#
# Order 631-wpkd (operator directive 2026-08-09): "our canonical place for
# skills should be ./skills/ and .claude/ and others like .opencode/ should not
# have exclusive skills, we don't do that in this project, everything is
# ephemeral and idempotent, no harness or agent specifics where we can avoid it".
#
# WHAT WENT WRONG. The layout section claimed each runtime reached skills through
# a symlink "so there is exactly one source of truth". It was false: .claude/
# held 10 symlinks and 14 real directories. Three hand-written project skills
# existed in exactly one harness —
#
#   build-macos-tray   .claude only  — a macOS BUILD skill invisible to a macOS
#                                      agent running under opencode/codex/gemini
#   haiku-delegate     .claude only
#   diagnose-forge     .opencode only
#
# — so what a host could DO depended on which harness launched it. That is
# precisely the harness-specific coupling the project forbids.
#
# THE DECLARED EXCEPTION, and why it is real rather than convenient.
# The openspec-* skills are GENERATED by the installed openspec CLI, not written
# here. They carry a `generatedBy: <version>` field and legitimately
# harness-specific content: Claude's copy has `allowed-tools:` frontmatter and
# names the AskUserQuestion tool, opencode's uses `/opsx-apply` where Claude's
# uses `/opsx:apply`. Four harnesses currently hold 44 such directories at three
# different generator versions (1.3.1 / 1.7.0 / 1.8.0).
#
# Canonicalizing them would fight the generator, which simply rewrites them on
# next launch — the churn already tracked by scripts/check-opsx-generated-dirt.sh.
# So they are EXEMPT BY NAME, and the exemption is narrow: it covers only
# directories matching the generated prefix. A hand-written skill can never
# qualify, because the test below also requires the generated marker.
#
# GRAMMAR — exactly one line:
#   ^(ok:skills-canonical|violation:harness-exclusive-skill):.*$
# Exit 0 when every non-generated skill is a symlink into canonical skills/.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 2

CANONICAL="skills"
HARNESSES=(.claude .opencode .codex .gemini .github)
GENERATED_PREFIX="openspec-"

violations=""
checked=0

for h in "${HARNESSES[@]}"; do
    [ -d "$h/skills" ] || continue
    for d in "$h"/skills/*; do
        [ -e "$d" ] || continue
        name="$(basename "$d")"
        checked=$((checked + 1))

        # A symlink is correct by construction — but it must point INTO the
        # canonical tree, not at some other harness's copy.
        if [ -L "$d" ]; then
            target="$(readlink "$d")"
            case "$target" in
                *"/${CANONICAL}/${name}"|"../../${CANONICAL}/${name}") ;;
                *) violations="${violations}${d} -> ${target} (symlink does not point into ${CANONICAL}/)"$'\n' ;;
            esac
            continue
        fi

        # A real directory is allowed ONLY if it is generated. Both conditions
        # must hold: the declared name prefix AND the generator's own marker.
        # Requiring the marker is what stops the exemption being used as a
        # loophole by anything hand-written.
        if [ "${name#"$GENERATED_PREFIX"}" != "$name" ] \
           && grep -qs 'generatedBy:' "$d/SKILL.md"; then
            continue
        fi

        violations="${violations}${d} (real directory; hand-written skills belong in ${CANONICAL}/ and are reached by symlink)"$'\n'
    done
done

if [ -n "$violations" ]; then
    echo "violation:harness-exclusive-skill:$(printf '%s' "$violations" | grep -c .) offender(s)"
    printf '%s' "$violations" | sed 's/^/  /'
    echo "  REMEDY: git mv <path> skills/<name> && ln -s ../../skills/<name> <path>"
    exit 1
fi

echo "ok:skills-canonical:${checked} entries checked across ${#HARNESSES[@]} harnesses"
