#!/usr/bin/env bash
# install-hooks.sh — Install git hooks for OpenSpec workflow
# @trace spec:spec-traceability, spec:versioning
#
# Installs two git hooks:
#   1. pre-commit: OpenSpec trace warnings and spec-cheatsheet drift checks
#   2. pre-push: VERSION guard (prevents VERSION modifications on non-main branches)
#
# Idempotent: safe to run multiple times. If hooks already exist and aren't ours,
# warns but does not overwrite (appends to existing).
#
# Usage: ./scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Ask Git for the path it will actually execute. This handles ordinary clones,
# linked worktrees, and core.hooksPath (the forge uses a shared external hooks
# directory). Writing unconditionally to .git/hooks can report success while
# every installed guard remains inert.
GIT_HOOKS_DIR="$(git -C "$REPO_ROOT" rev-parse --path-format=absolute --git-path hooks)"

# HOOK BODIES RESOLVE THE REPO ROOT AT RUN TIME, NEVER AT INSTALL TIME.
# Order 632-* (Windows host 2026-08-09). Baking "$REPO_ROOT" into the generated
# hook records the path as the INSTALLING shell saw it, and one checkout has
# more than one true path: WSL sees /mnt/c/Users/... while Git Bash sees
# /c/Users/... for the same bytes on disk. Hooks installed from WSL therefore
# made every `git commit` from the Windows shell die with
#   bash: /mnt/c/.../scripts/hooks/pre-commit-openspec.sh: No such file or directory
# — no commit, no push, and on a host whose exit contract REQUIRES a push, the
# whole cycle's work is stranded. The same trap fires for a moved or renamed
# checkout, and for a container that mounts the repo at a different prefix.
#
# Git runs hooks with the working directory at the top level, and
# `git rev-parse --show-toplevel` answers in whatever path vocabulary the
# CURRENT shell speaks. Resolving there costs one subprocess and makes the hook
# correct under every view of the checkout, so the generated bodies below
# interpolate no host paths at all.
HOOK_PREAMBLE='HOOK_ROOT="$(git rev-parse --show-toplevel)" || exit 1'

# Ensure hooks directory exists
mkdir -p "$GIT_HOOKS_DIR"

# --- Install pre-commit hook -----------------------------------------------

PRECOMMIT_SOURCE="$REPO_ROOT/scripts/hooks/pre-commit-openspec.sh"
PRECOMMIT_TARGET="$GIT_HOOKS_DIR/pre-commit"
PRECOMMIT_MARKER="# openspec-pre-commit-hook-v2"
PRECOMMIT_MARKER_OLD="# openspec-pre-commit-hook"
PRECOMMIT_REL="scripts/hooks/pre-commit-openspec.sh"

if [[ ! -f "$PRECOMMIT_SOURCE" ]]; then
    echo "error: $PRECOMMIT_SOURCE not found" >&2
    exit 1
fi

install_precommit() {
    cat > "$PRECOMMIT_TARGET" <<HOOK
#!/usr/bin/env bash
$PRECOMMIT_MARKER
# Generated by scripts/install-hooks.sh — edit the sources, not this file.
# No host path is baked in; see the HOOK_PREAMBLE rationale in the installer.
$HOOK_PREAMBLE
bash "\$HOOK_ROOT/$PRECOMMIT_REL"
HOOK
    chmod +x "$PRECOMMIT_TARGET"
}

if [[ -f "$PRECOMMIT_TARGET" ]] && grep -qF "$PRECOMMIT_MARKER" "$PRECOMMIT_TARGET" 2>/dev/null; then
    echo "✓ OpenSpec pre-commit hook already installed"
elif [[ -f "$PRECOMMIT_TARGET" ]] && grep -qF "$PRECOMMIT_MARKER_OLD" "$PRECOMMIT_TARGET" 2>/dev/null; then
    # A v1 hook carries an install-time absolute path and is broken under any
    # other path view of this checkout. Replace it rather than appending.
    install_precommit
    echo "✓ OpenSpec pre-commit hook upgraded to v2 (run-time root resolution)"
elif [[ -f "$PRECOMMIT_TARGET" ]]; then
    echo "⚠ an unrecognized pre-commit hook exists — leaving it alone" >&2
    echo "  To adopt the OpenSpec checks, move it aside and re-run this script." >&2
else
    install_precommit
    echo "✓ OpenSpec pre-commit hook installed"
fi

# --- Install pre-push hook -------------------------------------------------

PREPUSH_TARGET="$GIT_HOOKS_DIR/pre-push"
PREPUSH_MARKER="# tillandsias-pre-push-v4"

VERSION_GUARD_REL="scripts/hooks/pre-push-version-guard.sh"
LOCAL_GATE_REL="scripts/hooks/pre-push-local-gate.sh"
VERSION_GUARD="$REPO_ROOT/$VERSION_GUARD_REL"
LOCAL_GATE="$REPO_ROOT/$LOCAL_GATE_REL"

for src in "$VERSION_GUARD" "$LOCAL_GATE"; do
    if [[ ! -f "$src" ]]; then
        echo "error: $src not found" >&2
        exit 1
    fi
done

# The hook is GENERATED as one composed script rather than assembled by
# appending `bash <script>` lines, which was the previous scheme. Appending is
# subtly wrong: each `bash <script>` runs in a subshell, so a guard that exits 1
# does NOT stop the hook, and the hook's final exit status is whatever the LAST
# guard returned. A failing VERSION guard would be silently masked by a passing
# local gate. Composing with explicit `|| exit` makes the first failure decisive.
#
# v4 supersedes the v1/v2/v3 markers; an older hook is replaced. v3 differed only
# in baking install-time absolute paths, which broke it under a second path view
# of the same checkout (WSL /mnt/c vs Git Bash /c).
install_prepush() {
    cat > "$PREPUSH_TARGET" <<HOOK
#!/usr/bin/env bash
$PREPUSH_MARKER
# Generated by scripts/install-hooks.sh — edit the sources, not this file.
#
# Fail-fast composition: the first refusal wins. Do NOT convert this back into a
# list of bare \`bash <script>\` lines; subshell exits do not propagate and a
# failing guard would be masked by a later passing one.
#
# STDIN IS CAPTURED ONCE AND REPLAYED. Git supplies the ref list
# ("<local ref> <local sha> <remote ref> <remote sha>") on stdin, and a stream
# can only be consumed once — the first guard to read it would starve every
# guard after it. The VERSION guard needs that list to tell whether the commits
# being PUSHED touch VERSION, so it must not be the only one that can see it.
#
# No host path is baked in; see the HOOK_PREAMBLE rationale in the installer.
$HOOK_PREAMBLE
REFS="\$(cat)"
printf '%s\n' "\$REFS" | bash "\$HOOK_ROOT/$VERSION_GUARD_REL" "\$@" || exit \$?
printf '%s\n' "\$REFS" | bash "\$HOOK_ROOT/$LOCAL_GATE_REL"    "\$@" || exit \$?
HOOK
    chmod +x "$PREPUSH_TARGET"
}

if [[ -f "$PREPUSH_TARGET" ]] && grep -qF "$PREPUSH_MARKER" "$PREPUSH_TARGET" 2>/dev/null; then
    echo "✓ pre-push hook (VERSION guard + local gate) already installed"
elif [[ -f "$PREPUSH_TARGET" ]] && grep -qE "# (version-guard-hook|tillandsias-pre-push-v[23])" "$PREPUSH_TARGET" 2>/dev/null; then
    install_prepush
    echo "✓ pre-push hook upgraded to v4 (run-time root resolution)"
elif [[ -f "$PREPUSH_TARGET" ]]; then
    echo "⚠ an unrecognized pre-push hook exists — leaving it alone" >&2
    echo "  To adopt the Tillandsias gate, move it aside and re-run this script." >&2
else
    install_prepush
    echo "✓ pre-push hook installed (VERSION guard + local gate)"
fi

# --- Install post-commit hook -----------------------------------------------
# @trace gap:OBS-008

POSTCOMMIT_SOURCE="$REPO_ROOT/scripts/hooks/post-commit-dashboard-refresh.sh"
POSTCOMMIT_TARGET="$GIT_HOOKS_DIR/post-commit"
POSTCOMMIT_MARKER="# dashboard-refresh-hook-v2"
POSTCOMMIT_MARKER_OLD="# dashboard-refresh-hook"
POSTCOMMIT_REL="scripts/hooks/post-commit-dashboard-refresh.sh"

if [[ ! -f "$POSTCOMMIT_SOURCE" ]]; then
    echo "error: $POSTCOMMIT_SOURCE not found" >&2
    exit 1
fi

install_postcommit() {
    cat > "$POSTCOMMIT_TARGET" <<HOOK
#!/usr/bin/env bash
$POSTCOMMIT_MARKER
# Generated by scripts/install-hooks.sh — edit the sources, not this file.
# No host path is baked in; see the HOOK_PREAMBLE rationale in the installer.
$HOOK_PREAMBLE
bash "\$HOOK_ROOT/$POSTCOMMIT_REL"
HOOK
    chmod +x "$POSTCOMMIT_TARGET"
}

if [[ -f "$POSTCOMMIT_TARGET" ]] && grep -qF "$POSTCOMMIT_MARKER" "$POSTCOMMIT_TARGET" 2>/dev/null; then
    echo "✓ Dashboard refresh post-commit hook already installed"
elif [[ -f "$POSTCOMMIT_TARGET" ]] && grep -qF "$POSTCOMMIT_MARKER_OLD" "$POSTCOMMIT_TARGET" 2>/dev/null; then
    install_postcommit
    echo "✓ Dashboard refresh post-commit hook upgraded to v2 (run-time root resolution)"
elif [[ -f "$POSTCOMMIT_TARGET" ]]; then
    echo "⚠ an unrecognized post-commit hook exists — leaving it alone" >&2
else
    install_postcommit
    echo "✓ Dashboard refresh post-commit hook installed"
fi

echo ""
echo "All git hooks installed successfully."
