#!/usr/bin/env bash
# install-hooks.sh — Install git hooks for OpenSpec workflow
# @trace spec:spec-traceability, spec:versioning
#
# Installs three git hooks:
#   1. pre-commit: OpenSpec trace warnings and spec-cheatsheet drift checks
#   2. pre-push: linux-next merge gate (851-gpb5) + VERSION guard + local gate
#   3. post-commit: dashboard refresh + env-gated expert index refresh
#
# Idempotent: safe to run multiple times. If hooks already exist and aren't ours,
# warns but does not overwrite (appends to existing).
#
# Usage: ./scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Ask Git for the path it will actually execute. This handles ordinary clones,
# linked worktrees, and core.hooksPath (the forge uses a shared external hooks
# directory). Writing unconditionally to .git/hooks can report success while
# every installed guard remains inert.
GIT_HOOKS_DIR="$(git -C "$REPO_ROOT" rev-parse --path-format=absolute --git-path hooks)"

# HOOK BODIES RESOLVE THE REPO ROOT AT RUN TIME, NEVER AT INSTALL TIME.
# Order 632-* (Windows host 2026-08-09). Baking "$REPO_ROOT" into the generated
# hook records the path as the INSTALLING shell saw it, and one checkout has
# more than one true path: WSL sees /mnt/c/Users/... while Git Bash sees
# /c/Users/... for the same bytes on disk. Hooks installed from WSL therefore
# made every `git commit` from the Windows shell die with
#   bash: /mnt/c/.../scripts/hooks/pre-commit-openspec.sh: No such file or directory
# — no commit, no push, and on a host whose exit contract REQUIRES a push, the
# whole cycle's work is stranded. The same trap fires for a moved or renamed
# checkout, and for a container that mounts the repo at a different prefix.
#
# Git runs hooks with the working directory at the top level, and
# `git rev-parse --show-toplevel` answers in whatever path vocabulary the
# CURRENT shell speaks. Resolving there costs one subprocess and makes the hook
# correct under every view of the checkout, so the generated bodies below
# interpolate no host paths at all.
HOOK_PREAMBLE='HOOK_ROOT="$(git rev-parse --show-toplevel)" || exit 1'

# Ensure hooks directory exists
mkdir -p "$GIT_HOOKS_DIR"

# --- Install pre-commit hook -----------------------------------------------

PRECOMMIT_SOURCE="$REPO_ROOT/scripts/hooks/pre-commit-openspec.sh"
PRECOMMIT_TARGET="$GIT_HOOKS_DIR/pre-commit"
PRECOMMIT_MARKER="# openspec-pre-commit-hook-v2"
PRECOMMIT_MARKER_OLD="# openspec-pre-commit-hook"
PRECOMMIT_REL="scripts/hooks/pre-commit-openspec.sh"

if [[ ! -f "$PRECOMMIT_SOURCE" ]]; then
    echo "error: $PRECOMMIT_SOURCE not found" >&2
    exit 1
fi

install_precommit() {
    cat > "$PRECOMMIT_TARGET" <<HOOK
#!/usr/bin/env bash
$PRECOMMIT_MARKER
# Generated by scripts/install-hooks.sh — edit the sources, not this file.
# No host path is baked in; see the HOOK_PREAMBLE rationale in the installer.
$HOOK_PREAMBLE
bash "\$HOOK_ROOT/$PRECOMMIT_REL"
HOOK
    chmod +x "$PRECOMMIT_TARGET"
}

if [[ -f "$PRECOMMIT_TARGET" ]] && grep -qF "$PRECOMMIT_MARKER" "$PRECOMMIT_TARGET" 2>/dev/null; then
    echo "✓ OpenSpec pre-commit hook already installed"
elif [[ -f "$PRECOMMIT_TARGET" ]] && grep -qF "$PRECOMMIT_MARKER_OLD" "$PRECOMMIT_TARGET" 2>/dev/null; then
    # A v1 hook carries an install-time absolute path and is broken under any
    # other path view of this checkout. Replace it rather than appending.
    install_precommit
    echo "✓ OpenSpec pre-commit hook upgraded to v2 (run-time root resolution)"
elif [[ -f "$PRECOMMIT_TARGET" ]]; then
    echo "⚠ an unrecognized pre-commit hook exists — leaving it alone" >&2
    echo "  To adopt the OpenSpec checks, move it aside and re-run this script." >&2
else
    install_precommit
    echo "✓ OpenSpec pre-commit hook installed"
fi

# --- Install pre-push hook -------------------------------------------------

PREPUSH_TARGET="$GIT_HOOKS_DIR/pre-push"
PREPUSH_MARKER="# tillandsias-pre-push-v6"

MAIN_AFFORD_REL="scripts/hooks/pre-push-main-branch-affordance.sh"
MERGE_GATE_REL="scripts/hooks/pre-push-linux-next-merged.sh"
VERSION_GUARD_REL="scripts/hooks/pre-push-version-guard.sh"
LOCAL_GATE_REL="scripts/hooks/pre-push-local-gate.sh"
MAIN_AFFORD="$REPO_ROOT/$MAIN_AFFORD_REL"
MERGE_GATE="$REPO_ROOT/$MERGE_GATE_REL"
VERSION_GUARD="$REPO_ROOT/$VERSION_GUARD_REL"
LOCAL_GATE="$REPO_ROOT/$LOCAL_GATE_REL"

for src in "$MAIN_AFFORD" "$MERGE_GATE" "$VERSION_GUARD" "$LOCAL_GATE"; do
    if [[ ! -f "$src" ]]; then
        echo "error: $src not found" >&2
        exit 1
    fi
done

# The hook is GENERATED as one composed script rather than assembled by
# appending `bash <script>` lines, which was the previous scheme. Appending is
# subtly wrong: each `bash <script>` runs in a subshell, so a guard that exits 1
# does NOT stop the hook, and the hook's final exit status is whatever the LAST
# guard returned. A failing VERSION guard would be silently masked by a passing
# local gate. Composing with explicit `|| exit` makes the first failure decisive.
#
# v5 supersedes the v1/v2/v3/v4 markers; an older hook is replaced. v3 differed
# only in baking install-time absolute paths, which broke it under a second path
# view of the same checkout (WSL /mnt/c vs Git Bash /c). v5 adds the
# linux-next merge gate (order 851-gpb5) — methodology's
# pull_merge_cadence.pre_push_gate, previously enforced by no code — placed
# FIRST because it is the cheapest guard and its remediation (a merge) changes
# the tree, after which the other guards' verdicts would need re-deriving
# anyway.
install_prepush() {
    cat > "$PREPUSH_TARGET" <<HOOK
#!/usr/bin/env bash
$PREPUSH_MARKER
# Generated by scripts/install-hooks.sh — edit the sources, not this file.
#
# Fail-fast composition: the first refusal wins. Do NOT convert this back into a
# list of bare \`bash <script>\` lines; subshell exits do not propagate and a
# failing guard would be masked by a later passing one.
#
# STDIN IS CAPTURED ONCE AND REPLAYED. Git supplies the ref list
# ("<local ref> <local sha> <remote ref> <remote sha>") on stdin, and a stream
# can only be consumed once — the first guard to read it would starve every
# guard after it. The VERSION guard needs that list to tell whether the commits
# being PUSHED touch VERSION, so it must not be the only one that can see it.
#
# No host path is baked in; see the HOOK_PREAMBLE rationale in the installer.
$HOOK_PREAMBLE
REFS="\$(cat)"
printf '%s\n' "\$REFS" | bash "\$HOOK_ROOT/$MAIN_AFFORD_REL" "\$@" || exit \$?
printf '%s\n' "\$REFS" | bash "\$HOOK_ROOT/$MERGE_GATE_REL"    "\$@" || exit \$?
printf '%s\n' "\$REFS" | bash "\$HOOK_ROOT/$VERSION_GUARD_REL" "\$@" || exit \$?
printf '%s\n' "\$REFS" | bash "\$HOOK_ROOT/$LOCAL_GATE_REL"    "\$@" || exit \$?
HOOK
    chmod +x "$PREPUSH_TARGET"
}

if [[ -f "$PREPUSH_TARGET" ]] && grep -qF "$PREPUSH_MARKER" "$PREPUSH_TARGET" 2>/dev/null; then
    echo "✓ pre-push hook (linux-next merge gate + VERSION guard + local gate) already installed"
elif [[ -f "$PREPUSH_TARGET" ]] && grep -qE "# (version-guard-hook|tillandsias-pre-push-v[2345])" "$PREPUSH_TARGET" 2>/dev/null; then
    install_prepush
    echo "✓ pre-push hook upgraded to v6 (adds the main-branch affordance)"
elif [[ -f "$PREPUSH_TARGET" ]]; then
    echo "⚠ an unrecognized pre-push hook exists — leaving it alone" >&2
    echo "  To adopt the Tillandsias gate, move it aside and re-run this script." >&2
else
    install_prepush
    echo "✓ pre-push hook installed (linux-next merge gate + VERSION guard + local gate)"
fi

# --- Install post-commit hook -----------------------------------------------
# @trace gap:OBS-008, order:685-yidq
#
# The single post-commit hook composes TWO bodies: the dashboard refresh
# (unconditional, OBS-008) and, order 685-yidq, an ENV-GATED expert-index
# refresh for HOSTS that carry expert infra. The forge already refreshes its
# experts on commit via core.hooksPath (images/default/lib-common.sh); this
# extends the SAME proven hook body (scripts/hooks/post-commit-expert-refresh.sh,
# order 396) to bare-metal dev hosts and git-mirror containers, so a host expert
# index stops going stale between launches (the class behind 682-z5h8).
#
# THE GATE. The expert-refresh body runs ONLY when TILLANDSIAS_HOST_EXPERTS is a
# non-empty value in the committing shell's environment. Closed contract:
#   * set it (to "1") ONLY on machines that carry expert infra and want their
#     host index kept fresh — a bare-metal dev host (export from the login
#     profile) or a git-mirror container (export in its env).
#   * leave it UNSET everywhere else — GitHub CI, a plain end-user checkout, a
#     transient clone — and the expert body is a bounded no-op (the hook still
#     runs the dashboard body and exits 0). Nothing rebuilds, nothing is logged
#     as work. The gate is fail-safe: absent => do nothing.
# The dashboard body is unaffected by the gate and always runs.

POSTCOMMIT_SOURCE="$REPO_ROOT/scripts/hooks/post-commit-dashboard-refresh.sh"
POSTCOMMIT_TARGET="$GIT_HOOKS_DIR/post-commit"
POSTCOMMIT_MARKER="# tillandsias-post-commit-v4"
# Any hook THIS installer generated in the past, so a marker bump upgrades
# rather than stranding the host. The version-number alternative is deliberate:
# matching only the specific predecessors meant every bump turned every
# existing install into "an unrecognized post-commit hook — leaving it alone",
# so the installer could install fresh but never upgrade itself. Found on the
# v3 -> v4 bump, 2026-08-17: the regenerated dispatcher was silently declined
# on the host that had asked for it.
POSTCOMMIT_MARKER_OLD_RE="# (dashboard-refresh-hook(-v2)?|tillandsias-post-commit-v[0-9]+)"
POSTCOMMIT_REL="scripts/hooks/post-commit-dashboard-refresh.sh"
EXPERT_REFRESH_REL="scripts/hooks/post-commit-expert-refresh.sh"
DEV_HOST_EXPERTS_REL="scripts/dev-host-experts.sh"

if [[ ! -f "$POSTCOMMIT_SOURCE" ]]; then
    echo "error: $POSTCOMMIT_SOURCE not found" >&2
    exit 1
fi
if [[ ! -f "$REPO_ROOT/$EXPERT_REFRESH_REL" ]]; then
    echo "error: $REPO_ROOT/$EXPERT_REFRESH_REL not found" >&2
    exit 1
fi

install_postcommit() {
    cat > "$POSTCOMMIT_TARGET" <<HOOK
#!/usr/bin/env bash
$POSTCOMMIT_MARKER
# Generated by scripts/install-hooks.sh — edit the sources, not this file.
# No host path is baked in; see the HOOK_PREAMBLE rationale in the installer.
$HOOK_PREAMBLE
# Dashboard refresh (OBS-008) — always runs.
bash "\$HOOK_ROOT/$POSTCOMMIT_REL"
# Expert index refresh (685-yidq) — ONLY on hosts that opt in via
# TILLANDSIAS_HOST_EXPERTS. Absent => bounded no-op, never rebuilds on CI or a
# plain checkout. Best-effort like the body itself; never fails the commit.
#
# The declaration is RESOLVED here rather than inherited. A git hook runs with
# whatever environment the committing process had, so gating on an inherited
# variable meant the refresh had never once fired on either dev host — measured
# independently on macuahuitl and yoga, 2026-08-17. Sourcing the resolver makes
# the hook ask the host instead of hoping the caller was configured.
# The resolver refuses inside a forge and sets nothing without a host-local
# declaration, so CI and plain checkouts are unchanged.
if [ -f "\$HOOK_ROOT/$DEV_HOST_EXPERTS_REL" ]; then
    . "\$HOOK_ROOT/$DEV_HOST_EXPERTS_REL"
fi
if [ -n "\${TILLANDSIAS_HOST_EXPERTS:-}" ]; then
    bash "\$HOOK_ROOT/$EXPERT_REFRESH_REL" || true
fi
HOOK
    chmod +x "$POSTCOMMIT_TARGET"
}

if [[ -f "$POSTCOMMIT_TARGET" ]] && grep -qF "$POSTCOMMIT_MARKER" "$POSTCOMMIT_TARGET" 2>/dev/null; then
    echo "✓ post-commit hook (dashboard + env-gated expert refresh) already installed"
elif [[ -f "$POSTCOMMIT_TARGET" ]] && grep -qE "$POSTCOMMIT_MARKER_OLD_RE" "$POSTCOMMIT_TARGET" 2>/dev/null; then
    install_postcommit
    echo "✓ post-commit hook upgraded to v4 (dashboard + env-gated expert refresh, 685-yidq)"
elif [[ -f "$POSTCOMMIT_TARGET" ]]; then
    echo "⚠ an unrecognized post-commit hook exists — leaving it alone" >&2
else
    install_postcommit
    echo "✓ post-commit hook installed (dashboard + env-gated expert refresh)"
fi

echo ""
echo "All git hooks installed successfully."
