#!/usr/bin/env bash
# install-hooks.sh — Install git hooks for OpenSpec workflow
# @trace spec:spec-traceability, spec:versioning
#
# Installs two git hooks:
#   1. pre-commit: OpenSpec trace warnings and spec-cheatsheet drift checks
#   2. pre-push: VERSION guard (prevents VERSION modifications on non-main branches)
#
# Idempotent: safe to run multiple times. If hooks already exist and aren't ours,
# warns but does not overwrite (appends to existing).
#
# Usage: ./scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Ask Git for the path it will actually execute. This handles ordinary clones,
# linked worktrees, and core.hooksPath (the forge uses a shared external hooks
# directory). Writing unconditionally to .git/hooks can report success while
# every installed guard remains inert.
GIT_HOOKS_DIR="$(git -C "$REPO_ROOT" rev-parse --path-format=absolute --git-path hooks)"

# Ensure hooks directory exists
mkdir -p "$GIT_HOOKS_DIR"

# --- Install pre-commit hook -----------------------------------------------

PRECOMMIT_SOURCE="$REPO_ROOT/scripts/hooks/pre-commit-openspec.sh"
PRECOMMIT_TARGET="$GIT_HOOKS_DIR/pre-commit"
PRECOMMIT_MARKER="# openspec-pre-commit-hook"

if [[ ! -f "$PRECOMMIT_SOURCE" ]]; then
    echo "error: $PRECOMMIT_SOURCE not found" >&2
    exit 1
fi

if [[ -f "$PRECOMMIT_TARGET" ]]; then
    if grep -qF "$PRECOMMIT_MARKER" "$PRECOMMIT_TARGET" 2>/dev/null; then
        echo "✓ OpenSpec pre-commit hook already installed"
    else
        echo "Existing pre-commit hook found — appending OpenSpec checks..."
        echo "" >> "$PRECOMMIT_TARGET"
        echo "$PRECOMMIT_MARKER" >> "$PRECOMMIT_TARGET"
        echo "bash \"$PRECOMMIT_SOURCE\"" >> "$PRECOMMIT_TARGET"
        echo "✓ OpenSpec pre-commit hook appended"
    fi
else
    cat > "$PRECOMMIT_TARGET" <<HOOK
#!/usr/bin/env bash
$PRECOMMIT_MARKER
bash "$PRECOMMIT_SOURCE"
HOOK
    chmod +x "$PRECOMMIT_TARGET"
    echo "✓ OpenSpec pre-commit hook installed"
fi

# --- Install pre-push hook -------------------------------------------------

PREPUSH_TARGET="$GIT_HOOKS_DIR/pre-push"
PREPUSH_MARKER="# tillandsias-pre-push-v3"

VERSION_GUARD="$REPO_ROOT/scripts/hooks/pre-push-version-guard.sh"
LOCAL_GATE="$REPO_ROOT/scripts/hooks/pre-push-local-gate.sh"

for src in "$VERSION_GUARD" "$LOCAL_GATE"; do
    if [[ ! -f "$src" ]]; then
        echo "error: $src not found" >&2
        exit 1
    fi
done

# The hook is GENERATED as one composed script rather than assembled by
# appending `bash <script>` lines, which was the previous scheme. Appending is
# subtly wrong: each `bash <script>` runs in a subshell, so a guard that exits 1
# does NOT stop the hook, and the hook's final exit status is whatever the LAST
# guard returned. A failing VERSION guard would be silently masked by a passing
# local gate. Composing with explicit `|| exit` makes the first failure decisive.
#
# v3 supersedes the v1/v2 markers; an older hook is replaced.
install_prepush() {
    cat > "$PREPUSH_TARGET" <<HOOK
#!/usr/bin/env bash
$PREPUSH_MARKER
# Generated by scripts/install-hooks.sh — edit the sources, not this file.
#
# Fail-fast composition: the first refusal wins. Do NOT convert this back into a
# list of bare \`bash <script>\` lines; subshell exits do not propagate and a
# failing guard would be masked by a later passing one.
#
# STDIN IS CAPTURED ONCE AND REPLAYED. Git supplies the ref list
# ("<local ref> <local sha> <remote ref> <remote sha>") on stdin, and a stream
# can only be consumed once — the first guard to read it would starve every
# guard after it. The VERSION guard needs that list to tell whether the commits
# being PUSHED touch VERSION, so it must not be the only one that can see it.
REFS="\$(cat)"
printf '%s\n' "\$REFS" | bash "$VERSION_GUARD" "\$@" || exit \$?
printf '%s\n' "\$REFS" | bash "$LOCAL_GATE"    "\$@" || exit \$?
HOOK
    chmod +x "$PREPUSH_TARGET"
}

if [[ -f "$PREPUSH_TARGET" ]] && grep -qF "$PREPUSH_MARKER" "$PREPUSH_TARGET" 2>/dev/null; then
    echo "✓ pre-push hook (VERSION guard + local gate) already installed"
elif [[ -f "$PREPUSH_TARGET" ]] && grep -qE "# (version-guard-hook|tillandsias-pre-push-v2)" "$PREPUSH_TARGET" 2>/dev/null; then
    install_prepush
    echo "✓ pre-push hook upgraded to v3 (local gate, fail-fast, stdin replay)"
elif [[ -f "$PREPUSH_TARGET" ]]; then
    echo "⚠ an unrecognized pre-push hook exists — leaving it alone" >&2
    echo "  To adopt the Tillandsias gate, move it aside and re-run this script." >&2
else
    install_prepush
    echo "✓ pre-push hook installed (VERSION guard + local gate)"
fi

# --- Install post-commit hook -----------------------------------------------
# @trace gap:OBS-008

POSTCOMMIT_SOURCE="$REPO_ROOT/scripts/hooks/post-commit-dashboard-refresh.sh"
POSTCOMMIT_TARGET="$GIT_HOOKS_DIR/post-commit"
POSTCOMMIT_MARKER="# dashboard-refresh-hook"

if [[ ! -f "$POSTCOMMIT_SOURCE" ]]; then
    echo "error: $POSTCOMMIT_SOURCE not found" >&2
    exit 1
fi

if [[ -f "$POSTCOMMIT_TARGET" ]]; then
    if grep -qF "$POSTCOMMIT_MARKER" "$POSTCOMMIT_TARGET" 2>/dev/null; then
        echo "✓ Dashboard refresh post-commit hook already installed"
    else
        echo "Existing post-commit hook found — appending dashboard refresh..."
        echo "" >> "$POSTCOMMIT_TARGET"
        echo "$POSTCOMMIT_MARKER" >> "$POSTCOMMIT_TARGET"
        echo "bash \"$POSTCOMMIT_SOURCE\"" >> "$POSTCOMMIT_TARGET"
        echo "✓ Dashboard refresh post-commit hook appended"
    fi
else
    cat > "$POSTCOMMIT_TARGET" <<HOOK
#!/usr/bin/env bash
$POSTCOMMIT_MARKER
bash "$POSTCOMMIT_SOURCE"
HOOK
    chmod +x "$POSTCOMMIT_TARGET"
    echo "✓ Dashboard refresh post-commit hook installed"
fi

echo ""
echo "All git hooks installed successfully."
