#!/usr/bin/env bash
# test-json-query-jq-parity.sh — order 1375-rn9b.
#
# `tillandsias-plan json get` must print what jq prints, byte for byte, with
# the same exit status, on every filter in scripts/portability/jq-subset-corpus.txt
# (the bucket A/B shapes the gate scripts use). The expected output is a
# GOLDEN FILE generated from jq, not a live jq run, because the point of the
# verb is the hosts that have no jq (macOS, Windows): the parity must be
# checkable there too. Where jq IS present, the fixture also re-derives each
# case from it and reports `drift:` when jq disagrees with the golden (a jq
# version change), advisory, since the golden is what the verb promises.
#
#   ok:json-get-parity:<n>/<n>        every case matched (stdout bytes + rc)
#   mismatch:<n>:<filter>             one line per divergent case, then rc=1
#   blocked:json-get-absent           the binary has no `json` verb (pre-fix)
#
#   --regenerate   rewrite the golden from host jq (needs jq)
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORPUS="$ROOT/scripts/portability/jq-subset-corpus.txt"
GOLDEN="$ROOT/scripts/portability/jq-subset-golden.txt"

# shellcheck source=scripts/plan-binary-probe.sh
. "$ROOT/scripts/plan-binary-probe.sh" 2>/dev/null || true
PLAN="$(resolve_plan_binary 2>/dev/null)" || { echo "skip:json-get-parity:no-plan-binary"; exit 0; }

# Run one case under a tool; print its stdout followed by a final "rc=<n>".
# `set -f` so a filter's `*`-free text and flags are never globbed.
run_case() {
    tool="$1"; flags="$2"; filter="$3"; input="$4"
    set -f
    # shellcheck disable=SC2086
    if [ "$flags" = "_" ]; then set --; else set -- $flags; fi
    set +f
    if [ "$tool" = "jq" ]; then
        printf '%s' "$input" | jq "$@" "$filter"
    else
        printf '%s' "$input" | "$PLAN" json get "$@" "$filter"
    fi
    echo "rc=$?"
}

cases() { grep -v '^#' "$CORPUS" | grep -v '^[[:space:]]*$'; }

if [ "${1:-}" = "--regenerate" ]; then
    command -v jq >/dev/null 2>&1 || { echo "blocked:json-get-parity:regenerate-needs-jq"; exit 2; }
    tmp="$GOLDEN.tmp.$$"
    {
        printf '# jq-subset-golden.txt — generated by test-json-query-jq-parity.sh --regenerate\n'
        printf '# from %s. One block per corpus case: "@@case <n>", its stdout, "rc=<n>".\n' "$(jq --version)"
        n=0
        cases | while IFS="$(printf '\t')" read -r flags filter input; do
            n=$((n + 1))
            printf '@@case %d\n' "$n"
            run_case jq "$flags" "$filter" "$input" 2>/dev/null
        done
    } > "$tmp" && mv "$tmp" "$GOLDEN"
    echo "ok:json-get-parity:regenerated:$(grep -c '^@@case ' "$GOLDEN")"
    exit 0
fi

if ! "$PLAN" capabilities 2>/dev/null | grep -qx 'json'; then
    echo "blocked:json-get-absent"
    exit 1
fi
[ -f "$GOLDEN" ] || { echo "blocked:json-get-parity:golden-missing"; exit 1; }

have_jq=0
command -v jq >/dev/null 2>&1 && have_jq=1

golden_block() {
    awk -v want="@@case $1" '
        $0 == want { on = 1; next }
        /^@@case / { on = 0 }
        on { print }
    ' "$GOLDEN"
}

total=0
bad=0
drift=0
tab="$(printf '\t')"
while IFS="$tab" read -r flags filter input; do
    total=$((total + 1))
    want="$(golden_block "$total")"
    got="$(run_case plan "$flags" "$filter" "$input" 2>/dev/null)"
    if [ "$got" != "$want" ]; then
        echo "mismatch:$total:$filter"
        bad=$((bad + 1))
    fi
    if [ "$have_jq" -eq 1 ]; then
        live="$(run_case jq "$flags" "$filter" "$input" 2>/dev/null)"
        if [ "$live" != "$want" ]; then
            echo "drift:$total:$filter (host jq disagrees with the golden; advisory)"
            drift=$((drift + 1))
        fi
    fi
done < <(cases)

if [ "$total" -lt 60 ]; then
    echo "refused:json-get-parity:corpus-too-small:$total"
    exit 1
fi
if [ "$bad" -eq 0 ]; then
    echo "ok:json-get-parity:$total/$total"
    [ "$drift" -eq 0 ] || echo "note:json-get-parity:drift=$drift"
    exit 0
fi
echo "FAIL:json-get-parity:$((total - bad))/$total"
exit 1
